---
# SPDX-FileCopyrightText: © 2024 Matt Williams <matt.williams@bristol.ac.uk>
# SPDX-License-Identifier: MIT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conch
  labels:
    app: conch
spec:
  {{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: conch
  template:
    metadata:
      labels:
        app: conch
      annotations:  # Always restart the pod on a deploy to get new config
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: conch
          image: {{ print .Values.image.registry "/" }}{{ required "image_name must be set" .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
          args: ["--port={{ .Values.port }}", "--config=/config/conch.toml"]
          env:
            - name: RUST_LOG
              value: "{{ .Values.log_level }}"
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - mountPath: {{ required "signing_key_dir must be set" .Values.signing_key_dir | quote }}
              name: conch-signing-key-volume
              readOnly: true
            - mountPath: "/config"
              name: conch-config-volume
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
          - name: conch-signing-key-volume
            secret:
              secretName: "{{ .Values.ssh_signing_key_secret_name }}"
          - name: conch-config-volume
            configMap:
              name: conch-config
