# SPDX-FileCopyrightText: © 2024 Matt Williams <matt.williams@bristol.ac.uk>
# SPDX-License-Identifier: MIT

name: Build artefacts

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true

permissions: {}

jobs:
  build-release:
    name: "Build release (${{ matrix.target }})"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || '' }}
          fetch-depth: 0  # This is needed so that git-describe works properly to set the version
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Build OCI image
        run: oci/build.sh --release
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Publish OCI image
        run: |
          echo "Getting version and OCI tag"
          version=$(target/release/conch --version | tail -n1 | cut -d' ' -f 2)
          tag="ghcr.io/${{ github.repository }}:${version}"
          echo "Tagging as ${tag}"
          podman tag localhost/conch:latest "${tag}"
          echo "Pushing to ${tag}"
          podman push "${tag}"
      - name: Store build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: conch
          path: |
            target/release/conch
